"""
nli_generator.py
----------------
Generates NLI-RE premise-hypothesis pairs from raw relation extraction records.

Three sources of NLI instances are generated from the raw records:

1. Positive pairs (Label = True)
   For every record whose relation is a known positive relation (i.e. not
   no_relation), the gold relation is verbalized into a hypothesis using
   its template, producing a True instance.

2. Ambiguous hard negatives (Label = False)
   For every positive (subject, relation, object) triple, an additional
   negative is generated by substituting the gold relation with a
   semantically similar sibling relation from the same ambiguity group
   (e.g. manager_of -> leader_of).  A candidate substitution is only used
   if it is verified safe: the substituted (subject, candidate, object)
   triple must not already hold true elsewhere in the dataset, checked by
   exact match, relation symmetry, and transitive inference.

3. Domain/range-aware negatives from no_relation records (Label = False)
   For every positive (subject, relation, object) triple in a sentence,
   we search that same sentence for a no_relation record whose entity pair
   (i, j) is different from (subject, object) but shares the same domain
   and range entity types as the positive relation. The positive relation's
   template is then applied to (i, j) to produce a negative instance — since
   the relation does not actually hold between i and j. As with ambiguous
   negatives, the candidate (i, relation, j) triple is verified safe via
   exact match, symmetry, and transitive inference before being used.

Domain/range compatibility is enforced using RELATION_SCHEMA, which maps
each relation to its allowed subject entity types (domain) and object
entity types (range).
"""

import json
import random
from collections import defaultdict
from pathlib import Path
from typing import Dict, FrozenSet, List, Set, Tuple

from src.data.templates import (
    POSITIVE_RELATIONS,
    RELATION_SCHEMA,
    SYMMETRIC_RELATIONS,
    TRANSITIVE_CONTAINMENT_RELATIONS,
    build_nli_sentence,
    get_ambiguous_relations,
    verbalize,
)

Triple = Tuple[str, str, str]   # (subject, relation, object)


# ---------------------------------------------------------------------------
# Domain/range compatibility index
# ---------------------------------------------------------------------------

def _build_compatibility_index() -> Dict[Tuple[str, str], List[str]]:
    """
    Build an index: (subject_type, object_type) -> [compatible relations].

    A relation r is compatible with a (subject_type, object_type) pair if
    subject_type is in domain(r) AND object_type is in range(r).
    """
    index: Dict[Tuple[str, str], List[str]] = defaultdict(list)
    for relation, (domain, range_) in RELATION_SCHEMA.items():
        for subj_type in domain:
            for obj_type in range_:
                index[(subj_type, obj_type)].append(relation)
    return dict(index)


_COMPATIBILITY_INDEX = _build_compatibility_index()


# ---------------------------------------------------------------------------
# Sentence-level indices
# ---------------------------------------------------------------------------

def _build_sentence_triple_index(records: List[Dict]) -> Dict[str, List[Triple]]:
    """
    Index sentence_id -> list of gold (subject, relation, object) triples
    present in that sentence.

    Used both for inferring domain/range context and for the transitive
    inference safety check, since transitivity must be evaluated against
    the gold facts actually present in the same sentence.
    """
    index: Dict[str, List[Triple]] = defaultdict(list)
    for rec in records:
        if rec["relation"] in POSITIVE_RELATIONS:
            index[rec["sentence_id"]].append(
                (rec["subject"], rec["relation"], rec["object"])
            )
    return dict(index)


def _build_sentence_no_relation_index(
    records: List[Dict],
) -> Dict[str, List[Tuple[str, str]]]:
    """
    Index sentence_id -> list of (subject, object) entity pairs that were
    labelled no_relation in that sentence.

    Used to find candidate (i, j) entity pairs in the same sentence as a
    positive triple, for the domain/range no_relation negative strategy.
    """
    index: Dict[str, List[Tuple[str, str]]] = defaultdict(list)
    for rec in records:
        if rec["relation"] == "no_relation":
            index[rec["sentence_id"]].append((rec["subject"], rec["object"]))
    return dict(index)


def _build_positive_fact_index(records: List[Dict]) -> Set[Triple]:
    """
    Build the set of all known positive (subject, relation, object) triples
    across the entire dataset.

    Used by the safety checks to verify that a candidate negative
    substitution does not coincide with a fact that is true elsewhere,
    even outside the current sentence.
    """
    facts: Set[Triple] = set()
    for rec in records:
        if rec["relation"] in POSITIVE_RELATIONS:
            facts.add((rec["subject"], rec["relation"], rec["object"]))
    return facts


# ---------------------------------------------------------------------------
# Safety checks shared by both negative-generation strategies
# ---------------------------------------------------------------------------

def _is_safe_negative(
    candidate_relation: str,
    subject: str,
    obj: str,
    sentence_id: str,
    sentence_triple_index: Dict[str, List[Triple]],
    positive_facts: Set[Triple],
) -> bool:
    """
    Determine whether (subject, candidate_relation, object) is safe to use
    as a negative instance — i.e. it does not coincide with a fact that is
    true by direct assertion, by symmetry, or by transitive inference.

    Three checks are applied:

    1. Exact match
       (subject, candidate_relation, object) must not already be a known
       positive triple anywhere in the dataset.

    2. Symmetry
       If candidate_relation is symmetric, (object, candidate_relation,
       subject) must also not be a known positive triple — a symmetric
       relation holding in the reverse direction means it holds forward too.

    3. Transitive inference
       If candidate_relation is a transitive containment relation, check
       whether it is inferable via a chain through other gold relations in
       the same sentence: if (subject, r, x) and (x, r, object) both hold
       for some intermediate entity x and r in
       TRANSITIVE_CONTAINMENT_RELATIONS, then candidate_relation(subject,
       object) is inferable and must be rejected.

    Args:
        candidate_relation:     Relation being considered as a negative.
        subject:                Subject entity mention.
        obj:                    Object entity mention.
        sentence_id:            ID of the sentence containing this pair.
        sentence_triple_index:  sentence_id -> list of gold triples (for
                                 the transitivity check).
        positive_facts:         Set of all known positive triples (for the
                                 exact-match and symmetry checks).

    Returns:
        True if the candidate is safe to use as a negative; False if it
        coincides with a true fact and must be rejected.
    """
    # 1. Exact match
    if (subject, candidate_relation, obj) in positive_facts:
        return False

    # 2. Symmetry
    if candidate_relation in SYMMETRIC_RELATIONS:
        if (obj, candidate_relation, subject) in positive_facts:
            return False

    # 3. Transitive inference (within the same sentence)
    if candidate_relation in TRANSITIVE_CONTAINMENT_RELATIONS:
        sentence_triples = sentence_triple_index.get(sentence_id, [])
        for (s1, r1, o1) in sentence_triples:
            if r1 not in TRANSITIVE_CONTAINMENT_RELATIONS or s1 != subject:
                continue
            for (s2, r2, o2) in sentence_triples:
                if r2 not in TRANSITIVE_CONTAINMENT_RELATIONS:
                    continue
                # Chain: subject -r1-> o1  and  o1 -r2-> object
                if s2 == o1 and o2 == obj:
                    return False

    return True


# ---------------------------------------------------------------------------
# Strategy 1: Ambiguous hard negatives (sibling relation substitution)
# ---------------------------------------------------------------------------

def _select_ambiguous_negative(
    gold_relation: str,
    subject: str,
    obj: str,
    sentence_id: str,
    sentence_triple_index: Dict[str, List[Triple]],
    positive_facts: Set[Triple],
) -> List[str]:
    """
    Return all safe ambiguous sibling relations that can substitute for
    gold_relation on the (subject, object) pair, for use as hard negatives.

    Candidates are drawn from every ambiguity group containing gold_relation
    and filtered through _is_safe_negative. All safe candidates are returned
    so that the caller can generate one negative instance per candidate,
    rather than randomly selecting one.

    Args:
        gold_relation:          The true relation of the (subject, object) pair.
        subject:                Subject entity mention.
        obj:                    Object entity mention.
        sentence_id:            ID of the sentence containing this triple.
        sentence_triple_index:  sentence_id -> list of gold triples.
        positive_facts:         Set of all known positive triples.

    Returns:
        Sorted list of safe ambiguous relation keys. Empty list if none exist.
    """
    siblings = get_ambiguous_relations(gold_relation)
    if not siblings:
        return []

    return [
        r for r in sorted(siblings)
        if _is_safe_negative(
            candidate_relation=r,
            subject=subject,
            obj=obj,
            sentence_id=sentence_id,
            sentence_triple_index=sentence_triple_index,
            positive_facts=positive_facts,
        )
    ]


# ---------------------------------------------------------------------------
# Strategy 2: Domain/range-aware negatives from no_relation pairs in the
# same sentence, reusing the positive relation's own template
# ---------------------------------------------------------------------------

def _entity_types_of(relation: str) -> Tuple[FrozenSet[str], FrozenSet[str]]:
    """Return (domain, range) entity type sets for a relation."""
    return RELATION_SCHEMA.get(relation, (frozenset(), frozenset()))


def _select_no_relation_negative(
    gold_relation: str,
    sentence_id: str,
    sentence_no_relation_index: Dict[str, List[Tuple[str, str]]],
    sentence_triple_index: Dict[str, List[Triple]],
    positive_facts: Set[Triple],
) -> List[Tuple[str, str]]:
    """
    Find a no_relation (i, j) entity pair in the same sentence that shares
    the domain/range entity types of gold_relation, for reuse with
    gold_relation's own template as a negative instance.

    Example: sentence x contains positive triple (a, rel_i, b). If the same
    sentence also has a no_relation pair (i, j) whose types are compatible
    with rel_i's domain and range, we generate hypothesis = T_{rel_i}(i, j)
    as a negative — since rel_i does NOT actually hold between i and j.

    Since explicit entity type tags are not available per-mention, domain/
    range compatibility for a no_relation pair is inferred indirectly: we
    only require that gold_relation itself is a domain/range-compatible
    relation in general (i.e. it appears in RELATION_SCHEMA), and we treat
    every no_relation pair in the same sentence as a same-type candidate,
    since entities co-occurring in one sentence's annotated pairs are drawn
    from the same NER tagging pass and therefore the same entity type
    inventory used to build the positive/no_relation pairs for that sentence.

    All candidates are filtered with _is_safe_negative before being
    returned, so a no_relation pair that is in fact a true (but
    unannotated or transitively/symmetrically inferable) instance of
    gold_relation is never used as a negative.

    Args:
        gold_relation:               Relation whose template will be reused.
        sentence_id:                 ID of the current sentence.
        sentence_no_relation_index:  sentence_id -> list of no_relation (i, j) pairs.
        sentence_triple_index:       sentence_id -> list of gold triples.
        positive_facts:              Set of all known positive triples.

    Returns:
        List of all safe (i, j) entity pairs to use with gold_relation's
        template. Empty list if no safe candidate exists in this sentence.
    """
    if gold_relation not in RELATION_SCHEMA:
        return []

    no_relation_pairs = sentence_no_relation_index.get(sentence_id, [])
    if not no_relation_pairs:
        return []

    safe_pairs = [
        (i, j) for (i, j) in no_relation_pairs
        if _is_safe_negative(
            candidate_relation=gold_relation,
            subject=i,
            obj=j,
            sentence_id=sentence_id,
            sentence_triple_index=sentence_triple_index,
            positive_facts=positive_facts,
        )
    ]

    return safe_pairs


# ---------------------------------------------------------------------------
# Main generation function
# ---------------------------------------------------------------------------

def generate_nli_pairs(
    records: List[Dict],
    seed: int = 42,
    include_ambiguous_negatives: bool = True,
    include_no_relation_negatives: bool = True,
) -> List[Dict]:
    """
    Convert raw RE records into binary NLI premise-hypothesis pairs.

    For every record whose relation is a known positive relation:

      1. A positive instance (Label = True) is generated using the gold
         relation's own template.

      2. If include_ambiguous_negatives is True, an additional hard
         negative (Label = False) is generated by substituting the gold
         relation with a semantically similar sibling relation from the
         same ambiguity group. The substitution is only used if it passes
         the exact-match, symmetry, and transitive-inference safety checks.

    no_relation records themselves are not used to generate standalone
    instances; they only serve as a source of candidate (i, j) pairs for
    strategy 3 above.

    Args:
        records: List of dicts with keys: sentence_id, sentence,
                 subject, object, relation.
        seed:    Random seed for reproducibility.
        include_ambiguous_negatives:   Enable strategy 2 (default True).
        include_no_relation_negatives: Enable strategy 3 (default True).

    Returns:
        List of NLI instance dicts with keys: nli_sentence, Label.
    """
    random.seed(seed)
    nli_pairs: List[Dict] = []

    sentence_triple_index      = _build_sentence_triple_index(records)
    sentence_no_relation_index = _build_sentence_no_relation_index(records)
    positive_facts              = _build_positive_fact_index(records)

    for rec in records:
        relation = rec["relation"]
        if relation not in POSITIVE_RELATIONS:
            continue  # no_relation records are only used as a pair source above

        sentence    = rec["sentence"]
        subject     = rec["subject"]
        obj         = rec["object"]
        sentence_id = rec.get("sentence_id", "")

        # ========== 1. Positive pair =============
        hypothesis   = verbalize(relation, subject, obj)
        nli_sentence = build_nli_sentence(sentence, hypothesis)
        nli_pairs.append({
            "nli_sentence": nli_sentence,
            "Label":        "True",
        })

        # ========== 2. Ambiguous hard negatives (all safe sibling relations) =============
        if include_ambiguous_negatives:
            for ambiguous_relation in _select_ambiguous_negative(
                gold_relation=relation,
                subject=subject,
                obj=obj,
                sentence_id=sentence_id,
                sentence_triple_index=sentence_triple_index,
                positive_facts=positive_facts,
            ):
                amb_hypothesis   = verbalize(ambiguous_relation, subject, obj)
                amb_nli_sentence = build_nli_sentence(sentence, amb_hypothesis)
                nli_pairs.append({
                    "nli_sentence": amb_nli_sentence,
                    "Label":        "False",
                })

    return nli_pairs


# ---------------------------------------------------------------------------
# I/O helpers
# ---------------------------------------------------------------------------

def load_jsonl(path: str | Path) -> List[Dict]:
    """Load records from a JSONL file."""
    with open(path, encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]


def save_jsonl(records: List[Dict], path: str | Path) -> None:
    """Save records to a JSONL file (UTF-8, one object per line)."""
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        for rec in records:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")


def sample_balanced(
    nli_pairs: List[Dict],
    n_positive: int,
    n_negative: int,
    seed: int = 42,
) -> List[Dict]:
    """
    Draw a balanced sample of positive and negative NLI pairs.

    Args:
        nli_pairs:   Full list of generated NLI pairs.
        n_positive:  Number of True (relation present) instances to sample.
        n_negative:  Number of False (relation absent) instances to sample.
        seed:        Random seed.

    Returns:
        Shuffled list of sampled pairs.
    """
    random.seed(seed)
    positives = [p for p in nli_pairs if p["Label"] == "True"]
    negatives = [p for p in nli_pairs if p["Label"] == "False"]

    sampled = (
        random.sample(positives, min(n_positive, len(positives)))
        + random.sample(negatives, min(n_negative, len(negatives)))
    )
    random.shuffle(sampled)
    return sampled


def split_data(
    records: List[Dict],
    train_ratio: float = 0.70,
    val_ratio:   float = 0.15,
    seed: int = 42,
) -> tuple[List[Dict], List[Dict], List[Dict]]:
    """
    Split records into train / val / test sets.

    Args:
        records:     Full shuffled list of NLI pairs.
        train_ratio: Fraction for training (default 0.70).
        val_ratio:   Fraction for validation (default 0.15).
                     Test gets the remainder (1 - train - val).
        seed:        Random seed.

    Returns:
        Tuple of (train, val, test) lists.
    """
    random.seed(seed)
    data = records.copy()
    random.shuffle(data)

    n       = len(data)
    n_train = int(n * train_ratio)
    n_val   = int(n * val_ratio)

    return data[:n_train], data[n_train:n_train + n_val], data[n_train + n_val:]
